### ISSUE TITLE
Problem with aws-cron-job - authentication

### ISSUE THREAD

**Issue by divdax** [avramovic/aws-cron-job#6]
I set every env variables and the aws credentials are corrent. i also can run `php artisan aws:schedule:run`.

If i try to login into my site i only get a blank white site.

i cleared the cache, views, and tried to config:cache...

Any idea how to fix this problem?

```
[2018-09-12 11:49:01] production.ERROR: Error executing "DescribeInstances" on "https://ec2.eu-west-1.amazonaws.com"; AWS HTTP error: Client error: `POST https://ec2.eu-west-1.amazonaws.com` resulted in a `401 Unauthorized` response:
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to val (truncated...)
 AuthFailure (client): AWS was not able to validate the provided access credentials - <?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>AuthFailure</Code><Message>AWS was not able to validate the provided access credentials</Message></Error></Errors><RequestID>6b437223-6e2f-41aa-9242-d9aad33dfa0a</RequestID></Response>
[2018-09-12 11:49:01] production.ERROR: Undefined offset: 0 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 0 at /var/app/current/vendor/avram/aws-cron-job/src/Commands/AwsScheduleRunCommand.php:65)
[stacktrace]
#0 /var/app/current/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php(34): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined offse...', '/var/app/curren...', 65, Array)
#1 /var/app/current/vendor/avram/aws-cron-job/src/Commands/AwsScheduleRunCommand.php(65): Raven_Breadcrumbs_ErrorHandler->handleError(8, 'Undefined offse...', '/var/app/curren...', 65, Array)
#2 [internal function]: Avram\\AwsCronJob\\Commands\\AwsScheduleRunCommand->handle()
#3 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /var/app/current/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(184): Illuminate\\Container\\Container->call(Array)
#8 /var/app/current/vendor/symfony/console/Command/Command.php(251): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Command.php(171): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 /var/app/current/vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /var/app/current/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Avram\\AwsCronJob\\Commands\\AwsScheduleRunCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /var/app/current/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /var/app/current/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/app/current/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/app/current/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 {main}
"}
```

**Comment by avramovic** [comment]
> AWS was not able to validate the provided access credentials

I think this error message is pretty clear. Please double check your login credentials. Maybe they are correct, but don't have required permissions. Make sure your IAM user has all the `ec2:Describe*` permissions. If that's not enough, give it `arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess` permission also.

The second error message is caused by the first one.

**Comment by avramovic** [comment]
@divdax Any updates on this? Did you manage to make it work?

**Comment by avramovic** [comment]
Closing as there's no response from the OP
